image: php:7.3-fpm

pipelines:
  branches:
    master:
      - step:
          script:
            - apt-get update && apt-get install -qy zip unzip git curl libfreetype6-dev libjpeg62-turbo-dev libpng-dev
            - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            - docker-php-ext-install -j$(nproc) gd pdo_mysql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
  #          - ln -f -s .env.pipelines .env
            - ./vendor/bin/phpunit
          services:
            - mysql

  pull-requests:
    '**':
      - step:
          script:
            - apt-get update && apt-get install -qy zip unzip git curl libfreetype6-dev libjpeg62-turbo-dev libpng-dev
            - docker-php-ext-configure gd --with-freetype-dir=/usr/include/ --with-jpeg-dir=/usr/include/
            - docker-php-ext-install -j$(nproc) gd pdo_mysql
            - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
            - composer install
            #          - ln -f -s .env.pipelines .env
            - ./vendor/bin/phpunit
          services:
            - mysql

definitions:
  services:
    mysql:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'admin'
        MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: ''